"""empty message

Revision ID: 6fc994d2b91b
Revises: 87f650430d40
Create Date: 2020-11-09 15:50:56.720168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fc994d2b91b'
down_revision = '87f650430d40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gamer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gamer_id'], ['gamers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admins')
    # ### end Alembic commands ###
